spring:
  datasource:
    url: jdbc:mysql://${DB_ADDRESS}:3306/audb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  servlet:
    context-path: /uaa
  port: 5000

eureka:
  instance:
    prefer-ip-address: true
  client:
    security:
      basic:
        user: user
        password: password
    service-url:
      default-zone: http://${HOST_ADDRESS}:8761/eureka
    fetchRegistry: true

