server:
  port: 8888

spring:
  profiles:
    active: @activatedProfile@
  security:
    user:
      username: user
      password: password

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      default-zone: http://user:password@${HOST_ADDRESS}:8761/eureka
#    fetchRegistry: true
