spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/
          search-paths:
            - 'config-server/src/main/resources/shared-prod'
          timeout: 10
          username:
          password:
